global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'cluster-manager'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'cache-node-a'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'cache-node-b'
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'cache-node-c'
    static_configs:
      - targets: ['host.docker.internal:5003']

  - job_name: 'cache-node-d'
    static_configs:
      - targets: ['host.docker.internal:5004']
